name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install composer and dependencies
        uses: php-actions/composer@v6

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        env:
          XDEBUG_MODE: coverage
        with:
          configuration: phpunit.xml
          php_extensions: xdebug

      - name: Upload to Codecov
        if: always()
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV }}
          files: ./coverage/clover.xml
          verbose: true
